//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseAccepted
    {
        public int ExpenseReportId { get; set; }
        public int AmountPaid { get; set; }
        public System.DateTime PaymentDate { get; set; }
    
        public virtual ExpenseDetail ExpenseDetail { get; set; }
    }
}
