//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelDetail()
        {
            this.ExpenseDetails = new HashSet<ExpenseDetail>();
        }
    
        public int MRNumber { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime Applydate { get; set; }
        public string ReasonForTravel { get; set; }
        public System.DateTime TravelDate { get; set; }
        public string TravelMode { get; set; }
        public string FromCity { get; set; }
        public string ToCity { get; set; }
        public System.TimeSpan TravelDuration { get; set; }
        public string Status { get; set; }
    
        public virtual EmployeeMaster EmployeeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseDetail> ExpenseDetails { get; set; }
    }
}
